In [179]:
import yfinance as yf   # type: ignore

In [180]:
ticker_symbol = "AAPL"
ticker = yf.Ticker(ticker_symbol)

In [181]:
#historical_data = ticker.history(period="100d", interval='1d')
historical_data = ticker.history(start="2024-01-01", end="2024-4-30", interval='1d')
historical_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-01-02 00:00:00-05:00,186.658310,187.944930,183.406880,185.152283,82488700,0.0,0.0
2024-01-03 00:00:00-05:00,183.736010,185.391653,182.948077,183.765930,58414500,0.0,0.0
2024-01-04 00:00:00-05:00,181.671458,182.608991,180.404806,181.432098,71983600,0.0,0.0
2024-01-05 00:00:00-05:00,181.511879,182.279846,179.696654,180.703995,62303300,0.0,0.0
2024-01-08 00:00:00-05:00,181.611610,185.112398,181.023163,185.072495,59144500,0.0,0.0
...,...,...,...,...,...,...,...
2024-04-23 00:00:00-04:00,165.126031,166.823726,164.696606,166.673920,49537800,0.0,0.0
2024-04-24 00:00:00-04:00,166.314410,169.070681,165.984870,168.791061,48251800,0.0,0.0
2024-04-25 00:00:00-04:00,169.300369,170.378908,167.922233,169.659882,50558300,0.0,0.0
2024-04-26 00:00:00-04:00,169.649895,171.107909,168.950831,169.070679,44838400,0.0,0.0
2024-04-29 00:00:00-04:00,173.135155,175.791556,172.865532,173.264984,68169400,0.0,0.0